

const ActionType = {
    FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
    REMOVE_PRODUCT_REQUEST: "REMOVE_PRODUCT_REQUEST",
    FETCH_CATEGORY_REQUEST: "FETCH_CATEGORY_REQUEST",
    ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
    UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
    REMOVE_CATEGORY_REQUEST: "REMOVE_CATEGORY_REQUEST",

    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    REMOVE_PRODUCT_SUCCESS: "REMOVE_PRODUCT_SUCCESS",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    REMOVE_CATEGORY_SUCCESS: "REMOVE_CATEGORY_SUCCESS",

    SORT_NAME_DECS_PRODUCT: "SORT_NAME_DECS_PRODUCT",
    SORT_NAME_INCR_PRODUCT: "SORT_NAME_INCR_PRODUCT",
    SORT_INDEX_DECS_PRODUCT: "SORT_INDEX_DECS_PRODUCT",
    SORT_INDEX_INCR_PRODUCT: "SORT_INDEX_INCR_PRODUCT",
    SORT_NAME_DECS_CATEGORY: "SORT_NAME_DECS_CATEGORY",
    SORT_NAME_INCR_CATEGORY: "SORT_NAME_INCR_CATEGORY",
    SORT_INDEX_DECS_CATEGORY: "SORT_INDEX_DECS_CATEGORY",
    SORT_INDEX_INCR_CATEGORY: "SORT_INDEX_INCR_CATEGORY",

}

export default ActionType;